### ISSUE TITLE
Why not allow JSONPath notation?

### ISSUE THREAD

**Issue by VictorioBerra** [benday/build-utilities#11]
I find it odd we are restricted to only 3 levels deep of JSON.

Why not allow:

`store.book[0].title`

To target:

```json
{
    "store": {
        "book": [
            {
                "title": "bob"
            }
        ]
    }
}
```

Also, it would be even better if we could specify this in a large newline separated textbox kinda like the azure app services app settings box where you can pass them as arguments.

**Comment by benday** [comment]
Hi @VictorioBerra.  Thanks for the note. 

There's no real reason for limiting it to 3 levels of json other than that's the number I picked.  

The easiest fix for me would be to simply add more levels.  Is 4 enough?  Do you need more?  

I think that doing something like what you described where you can replace whole sections of json is compelling but I think it would probably need to be a new task so that I don't blow up a lot of people's builds.  Are you thinking that you'd have something like this in a textbox?

```
store.book[0].title="bob"
store.book[1].title="sally"
store.config.auth.key="password"
store.config.auth.max_password_attempts=3
```

-Ben

**Comment by VictorioBerra** [comment]
@benday Pretty much exactly like this https://marketplace.visualstudio.com/items?itemName=ThatBlokeCalledJay.thatblokecalledjay-setjsonproperty

It would be even better if I could do multiple at once without having to add a bunch of build-utilities task just to set a few appsettings.json secrets.

**Comment by benday** [comment]
So basically you'd describe the json that you want *using json* and then it gets merged into your target document?

**Comment by VictorioBerra** [comment]
Right imagine if you have an appsettings.json like this:

```json
{
    "Authentication": {
        "ClientId": "REPLACE_ME",
        "ClientSecret": "REPLACE_ME"
    }
}
```

This is an extremely common scenario. If you host on IIS, you have to ship one of these, or go get your secrets from Key Vault at runtime. And thats not always simple because then you still need secrets to auth to Key Vault.

There are other tasks that can help with this: https://marketplace.visualstudio.com/items?itemName=4tecture.Tokenizer

But they fall short in that you have to hard code tokens in your files.

Currently, I am using [the new Key Vault feature for the Pipelines Variable Groups where variables can be pulled in when your pipeline runs](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml#link-secrets-from-an-azure-key-vault). So right now, I have all my secrets from KV available to me in the form of pipeline variables `$(MyClientSecretFromKeyvault)`. So where your plugin would come into handy, would maybe be like so: PATH: `Authentication.ClientSecret` 
 VALUE: `$(MyClientSecretFromKeyvault)`.

In order to take multiple, you could do it the way the App Services pipeline works:

![image](https://user-images.githubusercontent.com/2934507/82242344-492f2700-9903-11ea-9464-952fa0008528.png)

So imagine you have a box called JSON Replacements with a value like so:

```
 -Authentication.ClientId $(MyClientIdFromKeyvault) -Authentication.ClientSecret $(MyClientSecretFromKeyvault)
```
