### ISSUE TITLE
Support arrays when setting App Setting Value

### ISSUE THREAD

**Issue by p0onage** [benday/build-utilities#38]
Hello, I currently have a structure like below 

```
  "FirstLevel": {
    "SecondLevel": ["36d3af75-092a-45ba-acde-d829235b92b5", "aff44d11-d9de-4411-a36e-04ce51e4f15c"]
  }
```

How do I set the value for the second level which is an array? Is this possible?

**Comment by benday** [comment]
@p0onage  -- I just added this feature in v3.1 of the extension.  https://marketplace.visualstudio.com/items?itemName=bendayconsulting.build-task

Here's an example of how to use it from a YAML build.  It should work just as well from a classic json build, too.  

`- task: setjsonvalue@3
  displayName: 'set 4 level json value as an array'
  inputs:
    filename: '$(build.artifactstagingdirectory)\json-editing\appsettings.json'
    numberOfLevels: '4'
    keyname1: 'one'
    keyname2: 'two'
    keyname3: 'three'
    keyname4: 'fourArray'
    valueToSet: 'yay 4 levels with arrays!'
    setValueAsArray: true
    valueToSet2: 'val2'
    valueToSet3: 'val3'
    valueToSet4: 'val4'
    valueToSet5: 'val5'
    valueToSet6: 'val6'
    valueToSet7: 'val7'
    valueToSet8: 'val8'
    valueToSet9: 'val9'`

**Comment by p0onage** [comment]
Thanks for the quick response, this is a way forward but unfortunately this will be slightly difficult to implement for me as the number of array items can change per environment. I was hoping to just dynamically set them from environment variables

**Comment by benday** [comment]
Doh! 🤣

Can you give me a sample of how that data would look in an environment variable? How do you want to call this task, ideally?

**Comment by p0onage** [comment]
It's fine honestly just changed to a string instead of an Array 

`    "SomeIds": ["36d3af75-092a-45ba-acde-d829235b92b5", "aff44d11-d9de-4411-a36e-04ce51e4f15c"]`
`    "SomeIds": "36d3af75-092a-45ba-acde-d829235b92b5,aff44d11-d9de-4411-a36e-04ce51e4f15c"`


The idea is these ids could change so we could have 3 ids for Prod and 2 for QA etc.. So I've just changed to a string and in code will just use `.split(',')?.some((o: string) =>`

thanks for your help!
Joshua
