### ISSUE TITLE
Update to .NET Core 3.0

### ISSUE THREAD

**Issue by frandi** [benday/build-utilities#5]
Hi, I've been using this utility for my projects in Azure DevOps, and I love it, thank you!

But I have a problem recently with my new project which uses `netcoreapp3.0` and `netstandard2.1`. I'd like to know if there's a plan to update it for the framework in the near future?

**Comment by benday** [comment]
Hi @frandi  -- Glad you're getting some use out of this!

Upgrading to .NET Core 3 is definitely on by radar.  I'm mostly just waiting until .NET Core 3 shows up on the Azure DevOps build servers.  

Are you mostly looking for the EF Core migration deploy task to be upgraded?  Have you tried it already?  What error(s) are you getting?

Thanks,
-Ben

**Comment by frandi** [comment]
@benday this is the error that I got:

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '3.0.0' was not found.
```

I tried adding the `Use .NET Core` task to use `SDK 3.x`, but then it complained with:

```
The specified framework 'Microsoft.AspNetCore.App', version '2.2.0' was not found.
```

**Comment by benday** [comment]
I'm not surprised that it isn't working at the moment.  Could you give me a little more info though?  Which task were you using?  Were you running this on the Microsoft-hosted Azure DevOps build servers?

**Comment by frandi** [comment]
I used `Set Connection String (appsettings.json)` and `Deploy Entity Framework Core Migrations` tasks on the `vs2017-win2016` agent.

**Comment by jtlevine** [comment]
I've also had issues when upgrading from .Net core 2.2 to 3.1. We are using the "Deploy Entity Framework Core Migrations" task. We're using a Microsoft hosted agent for our release pipeline. This is the error that occurs during the EF Core migrations step:
```
Microsoft.EntityFrameworkCore.Tools.CommandException: Your startup project 'Scribe' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.
```
Our startup project definitely does include a reference to `Microsoft.EntityFrameworkCore.Design` so I'm unsure where the error is coming from. I also tried adding the `Use .Net Core` task to use `SDK 3.1.x` but it hasn't helped.

**Comment by jtlevine** [comment]
Never mind, we figured out the issue and it wasn't related to the "Deploy Entity Framework Core Migrations" task. At some point a `<PrivateAssets>` tag was added to the `<PackageReference>` tag for our `Microsoft.EntityFrameworkCore.Design` reference, causing the package to not be included in our CI/CD artifact. Once we removed it, the task was able to find the package and run correctly. My bad!

**Comment by benday** [comment]
@jtlevine -- glad you figured it out!  and I'm glad it wasn't my fault!  lol
