### ISSUE TITLE
Set more value in one task.

### ISSUE THREAD

**Issue by ivanmordor** [benday/build-utilities#7]
Hello. I use tasks:
Set App Setting Value (app.config / web.config)
Set Connection String (app.config / web.config)
Set Connection String (appsettings.json)
Set string value in a json file (appsettings.json)
on the server TFS 2018.
in my web config, more than 30 settings that need to be changed. I use the task of changing settings 30 times. It is very uncomfortable. Is it possible to implement the replacement of several variables at once in one task?
Thank.

**Comment by benday** [comment]
That's an interesting idea.  What kind of values are you setting?  How would you like the user interface work for this feature?

**Comment by ivanmordor** [comment]
Hello. The values I use are:
1-5 connections to database / logs / notification systems.
1-30 app settings key-values.
Settings affect the operation in the service logic or operation intervals.
2 interface options.
 option number 1: add the "add" button, when pressed, a new line is added key - value
 option number 2: combine tasks on connections and settings, set the format in the description

Attached pictures with the interface.
I really like your tasks for the build. I really hope for the implementation of my proposal.
![easy_1](https://user-images.githubusercontent.com/57183173/67926053-11aa9880-fbc6-11e9-86c0-33127312a76f.png)
![hard_2](https://user-images.githubusercontent.com/57183173/67926058-14a58900-fbc6-11e9-89eb-00ab3a9977a4.png)
