### ISSUE TITLE
version 1.60 broke nested JSON values

### ISSUE THREAD

**Issue by SeanMartz** [benday/build-utilities#9]
Previously in the Set string value in a json file task, we could specify nested json values with `.` (dot) notation.

e.g.
```
"Parent":{
"child1": "someValue",
"child2":"someValue"
}
```

referenced via:
`Parent.child1`

as of 1.47 this worked. as of 1.60 it does not work, but does not fail. the task looks as though it completed successfully, and allows the release to complete successfully, without replacing the value in the JSON file.

**Comment by SeanMartz** [comment]
It appears that it is appending them at the end of the json file instead of modifying the inline json.

e.g. 
"Parent":{
"child1": "unreplacedValue"
}, 
"Parent.child1": "replacedValue"

**Comment by benday** [comment]
@SeanMartz --

Could you post a screenshot of the task's args?

Thanks,
-Ben

**Comment by SeanMartz** [comment]
![image](https://user-images.githubusercontent.com/12223671/68494581-a9d6fc00-021c-11ea-901b-dafb9e76cedb.png)

**Comment by benday** [comment]
@SeanMartz -- I'm surprised that that worked before.  Change the "Value depth" to 2 and set Level 1 to "Reports" and Level 2 to "URL".

**Comment by SeanMartz** [comment]
I suppose that's a bit of an obvious fix 😅

Cheers @benday. thanks for the quick response!
